# Generated by Django 3.2.21 on 2023-12-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supermarket', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_image/image', upload_to='product_images'),
        ),
    ]
