# Generated by Django 3.2.21 on 2023-12-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supermarket', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/static/product_images/Hobbit.jpg', upload_to='plane_images'),
        ),
    ]
